[tool.briefcase]
project_name = "Truth Table Generator"
bundle = "com.mueller14003.github"
version = "3.0.0"
url = "https://github.com/mueller14003/Truth-Table-Generator"
license = "BSD license"
author = 'Kyle Mueller'
author_email = "kyle.mueller.ghs@gmail.com"

[tool.briefcase.app.truthtablegenerator]
formal_name = "Truth Table Generator"
description = "A cross-platform Truth Table Generator written in Python."
icon = "src/truthtablegenerator/resources/truthtablegenerator"
sources = ['src/truthtablegenerator']
requires = []


[tool.briefcase.app.truthtablegenerator.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.truthtablegenerator.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.truthtablegenerator.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.truthtablegenerator.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.truthtablegenerator.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
